name = "cutgluebuild"
compatibility_date = "2025-08-25"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "cutgluebuild-db"
database_id = "6b98a428-d670-4a6b-b24e-cf4ddf362736"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cutgluebuild-db-prod"
database_id = "5413478b-b852-4a19-9dfb-0617c996c738"

[vars]
ENVIRONMENT = "development"
DOMAIN = "cutgluebuild.com"
BASE_URL = "https://cutgluebuild.com"
STRIPE_PUBLISHABLE_KEY = "pk_test_..."
STRIPE_WEBHOOK_SECRET = "whsec_..."

[env.production.vars]
ENVIRONMENT = "production"
DOMAIN = "cutgluebuild.com" 
BASE_URL = "https://cutgluebuild.com"
STRIPE_PUBLISHABLE_KEY = "pk_live_..."
STRIPE_WEBHOOK_SECRET = "whsec_..."

[env.production.ai]
binding = "AI"

# Services removed for Pages deployment
