name = "cutgluebuild-api"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "cutgluebuild-templates"
preview_bucket_name = "cutgluebuild-templates-preview"

[vars]
ENVIRONMENT = "production"

[[env.preview.r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "cutgluebuild-templates-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
